# This config file doesn't do anything, because I don't have a personal GCP
# account and I don't fancy actually deploying this on my company's clusters
version: 2.1
executors:
  default-builder-image:
    docker:
      - image: some.gcp.url/project/default-builder-image:42
        auth:
          username: _json_key
          password: $ENV_VAR_PW
    environment:
      APP_NAME: iris-service
      GCLOUD_PROJECT: project-name
      GCLOUD_CLUSTER: cluster42
      DOCKER_IMAGE: some.gcp.url/project/$PROJECT_NAME:$CIRCLE_BUILD_NUM

jobs:
  build_and_deploy:
    executor: default-builder-image
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Building iris-service image and saving on GCP
          command: ./.circleci/build_image.sh
          environment:
            DOCKERFILE_LOCATION: Dockerfile
      - run: 
          name: Deploy iris-service
          command: ./.circleci/deploy.sh
          environment:
            NAMESPACE: default
           
  
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master